from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4c0cc9bf8c'
down_revision = '7328e6e88a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###