from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc76f813a47'
down_revision = 'c0e29cdad763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###